health/urls.py
from django.urls import path,include
from health import views
from allauth.account.views import SignupView

urlpatterns = [
    path('',views.user_login,name='login'),
    path('login/doc/dochome/',views.dochome,name='dochome'),
    path('login/recep/recephome/', views.recephome, name='recephome'),
    path('login/lab/labhome/', views.labhome, name='labhome'),
    path('login/patient/patienthome/', views.patienthome, name='patienthome'),
    path('signup/doc/dochome/',views.dochome,name='dochome'),
    path('signup/recep/recephome/', views.recephome, name='recephome'),
    path('signup/lab/labhome/', views.labhome, name='labhome'),
    path('signup/patient/patienthome/', views.patienthome, name='patienthome'),
    path('doc/schedule/',views.doc_schedule,name='doc_schedule'),
    path('doc/search_patient/',views.search_patient,name='search_patient'),
    path('doc/patient_result/',views.patient_result,name='patient_result'),
    path('doc/pasche/<int:patient>/',views.doc_schedule_result,name='doc_schedule_result'),
    path('doc/edit_schedule/<int:scheduleID>/',views.edit_schedule,name='edit_schedule'),
    path('doc/request_lab/<int:schedule>/',views.request_lab,name='request_lab'),
    path('lab/test/', views.show_test, name='show_test'),
    path('lab/upload_result/<int:testID>/', views.upload_result, name='upload_result'),
    path('recep/book_appoint/', views.recep_book_appoint, name='recep_book'),
    path('recep/cancel_appoint/<int:scheduleID>/', views.recep_cancel_appoint, name='recep_cancel'),
    path('recep/schedule/', views.recep_schedule, name='recep_schedule'),
    path('patient/book_appoint/', views.patient_book_appoint, name='patient_book'),
    path('patient/cancel_appoint/<int:scheduleID>/', views.patient_cancel_appoint, name='patient_cancel'),
    path('patient/schedule/<int:nin>/', views.patient_show_schedule, name='patient_schedule'),
    path('patient/schedule_detail/<int:schedule>/', views.patient_scheDetail, name='patient_scheDetail'),
    path('patient/PHR/<int:nin>/', views.myPHR, name='myPHR'),

]

myhealth/urls.py
from django.urls import path, include
from django.contrib import admin
from health import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/login/', views.user_login, name='login'),
    path('admin/', admin.site.urls),
    path('', include('health.urls')),
    path('', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

health/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.db.utils import IntegrityError
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.validators import FileExtensionValidator


class User(AbstractUser):

    USER_TYPE_CHOICES = (
      (1, 'Doctor'),
      (2, 'Lab People'),
      (3, 'Receptionist'),
      (4, 'Patient'),
      (5, 'Administration'),
    )
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES,null=True)
    sex = models.BooleanField(blank=True, null=True)
    tel_no = models.CharField(max_length=255, blank=True, null=True)
    dob = models.DateField(db_column='DOB', blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    REQUIRED_FIELDS = ['user_type','email','password',]

    def __str__(self):
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        return "/health/%i/" % (self.pk)


class Department(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(max_length=255)
    hospital = models.ForeignKey('Hospital', on_delete=models.CASCADE, db_column='hospital',blank=True, null=True)  # Field name made lowercase.
    tel_no = models.CharField(max_length=255)

    class Meta:
        db_table = 'Department'


class Disease(models.Model):
    name = models.CharField(max_length=255,primary_key=True)

    class Meta:
        db_table = 'Disease'

    @classmethod
    def create(cls, name):
        dis = cls(name=name)
        # do something with the book
        return dis


class Ehr(models.Model):
    schedule = models.ForeignKey('Schedule', db_column='schedule', on_delete=models.CASCADE)
    medicalsupply = models.ForeignKey('MedicalSupply',on_delete=models.CASCADE,null=True,blank=True)  # Field name made lowercase.
    amount = models.IntegerField(default=0,null=True,blank=True)

    class Meta:
        db_table = 'EHR'
        unique_together = (('schedule', 'medicalsupply'),)

    @classmethod
    def create(cls, schedule,medicalsupply,amount):
        ehr = cls(schedule=schedule,medicalsupply=medicalsupply,amount=amount)
        # do something with the book
        return ehr


class Hospital(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(max_length=255,unique=True)
    address = models.CharField(max_length=255)

    class Meta:
        db_table = 'Hospital'

    @classmethod
    def create(cls, name,address):
        hospital = cls(name=name,address=address)
        # do something with the book
        return hospital


class LabTest(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    done = models.BooleanField(default=False)
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column='patient')
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column='doctor',related_name='doc')
    name = models.CharField(max_length=255,null=True,blank=True)
    conductor = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING, db_column='conductor',related_name='conduct',null=True,blank=True)
    report = models.FileField(upload_to='report/',validators=[FileExtensionValidator(allowed_extensions=['pdf'])],null=True,blank=True)

    class Meta:
        db_table = 'Lab test'


class MedicalSupply(models.Model):
    name = models.CharField(max_length=255)
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    stock = models.IntegerField(default=0)

    class Meta:
        db_table = 'Medical supply'

    @classmethod
    def create(cls, name,stock):
        ms = cls(name=name,stock=stock)
        # do something with the book
        return ms


class Order(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    datetime = models.DateTimeField(default = timezone.now)

    class Meta:
        db_table = 'Order'

    @classmethod
    def create(cls, datetime):
        order = cls(datetime=datetime)
        # do something with the book
        return order


class Orderdetail(models.Model):
    orderid = models.ForeignKey('Order', db_column='orderID', on_delete=models.CASCADE)  # Field name made lowercase.
    medicalsupply = models.ForeignKey('MedicalSupply', on_delete=models.CASCADE, db_column='medicalSupply')  # Field name made lowercase.
    amount = models.IntegerField()

    class Meta:
        db_table = 'OrderDetail'
        unique_together = (('orderid', 'medicalsupply'),)


class Phr(models.Model):
    patient = models.OneToOneField(settings.AUTH_USER_MODEL, db_column='patient', primary_key=True, on_delete=models.CASCADE,related_name='phr_pat')
    weight = models.DecimalField(max_digits=65535, decimal_places=2, blank=True, null=True)
    height = models.DecimalField(max_digits=65535, decimal_places=2, blank=True, null=True)
    doctorid = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column='doctorID', blank=True, null=True,related_name='phr_doc')  # Field name made lowercase.
    disease = models.ForeignKey('Disease', on_delete=models.CASCADE, db_column='disease', blank=True, null=True)

    class Meta:
        db_table = 'PHR'


class Schedule(models.Model):
    checked_in = models.BooleanField(default=False)  #whether the patient has checked in or not
    booked = models.BooleanField(default=False)
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column='patient',blank=True,null=True,related_name='sche_pat')
    date = models.DateField(blank=True,null=True)  # Field renamed to remove unsuitable characters.
    time = models.TimeField(blank=True,null=True)
    doctorid = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column='doctorID', blank=True, null=True,related_name='sche_doc')
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    sysmptoms = models.TextField(max_length=65535,blank=True, null=True)
    diagnosis = models.TextField(max_length=65535,blank=True, null=True)
    prescriptions = models.TextField(max_length=65535,blank=True, null=True)
    treatment = models.TextField(max_length=65535,blank=True, null=True)
    waiting_time = models.TimeField(db_column='waiting time',blank=True,null=True)  # Field renamed to remove unsuitable characters.

    class Meta:
        db_table = 'Schedule'

    @classmethod
    def create(cls, checked_in,patient,date,time,doctorid):
        schedule = cls(checked_in=checked_in,patient=patient,date=date,time=time,doctorid=doctorid)
        # do something with the book
        return schedule

health/forms.py
from django import forms
from health.models import User, Department, Disease, Ehr,Hospital,LabTest
from health.models import MedicalSupply,Order,Orderdetail,Phr,Schedule
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from health.widgets import SelectTimeWidget
from datetimewidget.widgets import DateWidget,TimeWidget

class CustomUserCreationForm(UserCreationForm):

    tel_no = forms.CharField(max_length=255, label='Telephone number')
    dob = forms.DateField(label='Date of Birth',input_formats=['%Y/%m/%d'],help_text='YYYY/mm/dd')
    SEX = [('yes','Female'),('no','Male')]
    sex = forms.BooleanField(label='Sex',widget=forms.Select(choices = SEX))


    class Meta(UserCreationForm):
        model = User
        fields = ('email','user_type','first_name','last_name','sex','tel_no','dob','address','password',)

    # def __init__(self,user,*args,**kwargs):



class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email','user_type','first_name','last_name','sex','tel_no','dob','address',)


class SignupForm(forms.ModelForm):
    tel_no = forms.CharField(max_length=255, label='Telephone number')
    dob = forms.DateField(label='Date of Birth', input_formats=['%Y-%m-%d'],help_text='YYYY-mm-dd')
    SEX = [('yes','Female'),('no','Male')]
    sex = forms.BooleanField(label='Sex',widget=forms.Select(choices = SEX))

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.user_type = self.cleaned_data['user_type']
        user.sex = self.cleaned_data['sex']
        user.tel_no = self.cleaned_data['tel_no']
        user.dob = self.cleaned_data['dob']
        user.address = self.cleaned_data['address']
        user.save()

    class Meta:
        model = User
        fields = ('email','user_type','first_name','last_name','sex','tel_no','dob','address',)

class NoteForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ('sysmptoms','treatment','prescriptions','diagnosis',)


class DepartmentForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    tel_no = forms.CharField(max_length=255)
    class Meta:
        model = Department
        exclude = ('hospital',)

class DiseaseForm(forms.ModelForm):
    class Meta:
        model = Disease
        fields = ('name',)

class EhrForm(forms.ModelForm):
    amount = forms.IntegerField()
    class Meta:
        model = Ehr
        exclude = ('medicalsupply',)
        unique_together = (('schedule', 'medicalsupply'),)

class HospitalForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    class Meta:
        model = Hospital
        fields = ('id','name','address',)

class LabTestForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    report = forms.FileField(required=False)
    conductor = forms.ModelChoiceField(queryset=get_user_model().objects,required=False)
    class Meta:
        model = LabTest
        exclude = ('id','done',)

class ReportForm(forms.ModelForm):

    class Meta:
        model = LabTest
        fields = ('report',)

class MedicalSupplyForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    stock = forms.IntegerField()
    class Meta:
        model = MedicalSupply
        fields = ('id','name','stock',)

class OrderForm(forms.ModelForm):
    datetime = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'])
    class Meta:
        model = Order
        fields = ('id','datetime',)

class OrderdetailForm(forms.ModelForm):
    class Meta:
        model = Orderdetail
        exclude = ('medicalsupply',)
        unique_together = (('orderid', 'medicalsupply'),)

class PhrForm(forms.ModelForm):
    class Meta:
        model = Phr
        exclude = ('doctorid','disease','patient',)

# class PatientForm(forms.ModelForm):
#     class Meta:
#         model = Patient
#         exclude = ('user',)

class ScheduleForm(forms.ModelForm):
    # date = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'])
    date = forms.DateField(input_formats=['%d/%m/%Y'])
    time = forms.TimeField(widget=SelectTimeWidget(minute_step=15))
    doctorid = forms.ModelChoiceField(label = 'Doctor',queryset=get_user_model().objects,required=False)
    class Meta:
        model = Schedule
        fields = ('patient','time','doctorid','date',)

templates/health/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
  {% block headblock %}{% endblock %}

<!-- Custom styles for sidebar-->
  <link href="{% static "css/sidebar.css" %}" rel="stylesheet">

</head>

<body id="page-top">

  <div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  {% block topic1 %}{%endblock%}
  {% block topic2 %}{%endblock%}
  {% block topic3 %}{%endblock%}
  {% block topic4 %}{%endblock%}
  {% block topic5 %}{%endblock%}
</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">&#9776; Toggle Sidebar</button>
  <h2>Hi! {{current.first_name}}</h2>
  <p><a href="{% url 'account_logout' %}">logout</a></p>
  <p>{% block bodyblock %}{%endblock%}</p>
</div>

  <!-- Sidebar scripts for this page -->
  <script src="{% static "js/sidebar.js" %}"></script>

</body>

</html>

templates/health/create_account.html
{% extends 'health/base.html' %}
{% load static %}
{% block topic1 %}
<a href="{% url 'create_account' %}">Create an account</a>
{%endblock%}
{% block bodyblock %}
<h2>Create an account</h2>
<div class="wrapper">
  <form id="user_form" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <!-- First name:<br>
    <input type="text" name="firstname"><br>
    Last name:<br>
    <input type="text" name="lastname"><br>
    E-mail:<br>
    <input type="email" name="email"><br>
    Password:<br>
    <input type="password" name="psw"><br>
    User Type:<br>
    <select name="usertype">
      <option value=1>Doctor</option>
      <option value=2>Lab People</option>
      <option value=3>Receptionist</option>
      <option value=4>Patient</option>
      <option value=5>Administration</option>
    </select><br>
  </form>
  <form id="profile_form" method="post" action="/health/edit_profile/">
    Sex:<br>
    <select name="sex">
      <option value=True>Female</option>
      <option value=False>Male</option>
    </select><br>
    Telephone:<br>
    <input type="tel" name="phone" pattern="[0-9]{3}-[0-9]{4}-[0-9]{4}"><br>
    Department:<br>
    <input type="text" name="department"><br>
    Hospital:<br>
    <input type="text" name="hospital"><br>
    Birthday:<br>
    <input type="date" name="bday"><br>
    Address:<br>
    <input type="text" name="address"><br> -->
    <input type="submit" name="submit">

  </form>
</div>
{%endblock%}

templates/health/doc_EHR.html
{% extends 'health/dochome.html' %}
{% load static %}

{% block headblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <!-- make panel clickable -->
  <script src="{% static "js/schedule_panel.js" %}"></script>
  <link href="{% static "css/schedule_panel.css" %}" rel="stylesheet">
{% endblock %}

{% block bodyblock %}
{% if schedule %}
  {% for s in schedule %}
  <div class="panel panel-default">
    <div class="panel-heading">Appointment</div>
    <div class="panel-body" style="text-align:center">
      <a href="{% url 'edit_schedule' s.id %}">
      {{s.date}}{{s.time}}
      </a>
    </div>
  </div>
  {% endfor %}
{% endif %}
{%endblock%}

templates/health/edit_PHR.html
{% extends 'health/base.html' %}
{% load static %}
{% block topic1 %}
<a href="{% url 'patient_book' %}">Book an appointment</a>
{%endblock%}

{% block topic2 %}
<a href="{% url 'patient_cancel' %}">Cancel an appointment</a>
{%endblock%}

{% block topic3 %}
<a href="{% url 'myPHR' current.id %}">My PHR</a>
{%endblock%}

{% block topic4 %}
<a href="{% url 'edit_PHR' current.id %}">Edit My PHR</a>
{%endblock%}

{% block topic5 %}
<a href="{% url 'patient_schedule' current.id %}">My schedule</a>
{%endblock%}

{% block bodyblock %}
Click on the sidebar for further functions!
{%endblock%}

templates/health/login.html
<!-- <h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form> -->
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
  <!-- Custom styles for login page-->
    <link href="{% static "css/login.css" %}" rel="stylesheet">

</head>
<body>
<form class='login-form'>
  {% csrf_token %}
  <div class="flex-row">
    <label class="lf--label" for="username">
      <svg x="0px" y="0px" width="12px" height="13px">
        <path fill="#B1B7C4" d="M8.9,7.2C9,6.9,9,6.7,9,6.5v-4C9,1.1,7.9,0,6.5,0h-1C4.1,0,3,1.1,3,2.5v4c0,0.2,0,0.4,0.1,0.7 C1.3,7.8,0,9.5,0,11.5V13h12v-1.5C12,9.5,10.7,7.8,8.9,7.2z M4,2.5C4,1.7,4.7,1,5.5,1h1C7.3,1,8,1.7,8,2.5v4c0,0.2,0,0.4-0.1,0.6 l0.1,0L7.9,7.3C7.6,7.8,7.1,8.2,6.5,8.2h-1c-0.6,0-1.1-0.4-1.4-0.9L4.1,7.1l0.1,0C4,6.9,4,6.7,4,6.5V2.5z M11,12H1v-0.5 c0-1.6,1-2.9,2.4-3.4c0.5,0.7,1.2,1.1,2.1,1.1h1c0.8,0,1.6-0.4,2.1-1.1C10,8.5,11,9.9,11,11.5V12z"/>
      </svg>
    </label>
    <input id="username" class='lf--input' placeholder='Email address' type='text'>
  </div>
  <div class="flex-row">
    <label class="lf--label" for="password">
      <svg x="0px" y="0px" width="15px" height="5px">
        <g>
          <path fill="#B1B7C4" d="M6,2L6,2c0-1.1-1-2-2.1-2H2.1C1,0,0,0.9,0,2.1v0.8C0,4.1,1,5,2.1,5h1.7C5,5,6,4.1,6,2.9V3h5v1h1V3h1v2h1V3h1 V2H6z M5.1,2.9c0,0.7-0.6,1.2-1.3,1.2H2.1c-0.7,0-1.3-0.6-1.3-1.2V2.1c0-0.7,0.6-1.2,1.3-1.2h1.7c0.7,0,1.3,0.6,1.3,1.2V2.9z"/>
        </g>
      </svg>
    </label>
    <input id="password" class='lf--input' placeholder='Password' type='password'>
  </div>
  <input class='lf--submit' type='submit' value='LOGIN'>
</form>
</body>

templates/health/patient_EHR.html
{% extends 'health/base.html' %}
{% load static %}
{% block topic1 %}
<a href="{% url 'patient_book' %}">Book an appointment</a>
{%endblock%}

{% block topic2 %}
<a href="{% url 'patient_cancel' %}">Cancel an appointment</a>
{%endblock%}

{% block topic3 %}
<a href="{% url 'patient_EHR' %}">My EHR</a>
{%endblock%}

{% block topic4 %}
<a href="{% url 'edit_EHR' %}">Edit My EHR</a>
{%endblock%}

{% block bodyblock %}
Click on the sidebar for further functions!
{%endblock%}

templates/health/patient_book_appoint.html
{% extends 'health/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block headblock%}
<!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

<!-- CDN for widget_tweaks -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

{% endblock %}

{% block topic1 %}
<a href="{% url 'patient_book' %}">Book an appointment</a>
{%endblock%}

{% block topic3 %}
<a href="{% url 'myPHR' current.id %}">My PHR</a>
{%endblock%}

{% block topic4 %}
<a href="{% url 'patient_schedule' current.id %}">My appointment</a>
{%endblock%}

{% block bodyblock %}
<form  action="" method="POST">
  {% csrf_token %}

    <div class="form-group">
      <label for="{{ form.patient.id_for_label }}">{{ form.patient.label }}</label>
      {{ form.patient|add_class:'form-control' }}
      {% for error in form.patient.errors %}
        <span class="help-block">{{ error }}</span>
      {% endfor %}

      <label for="{{ form.doctorid.id_for_label }}">{{ form.doctorid.label }}</label>
      {{ form.doctorid|add_class:'form-control' }}
      {% for error in form.doctorid.errors %}
        <span class="help-block">{{ error }}</span>
      {% endfor %}

      <br><label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
      {{ form.date }}<br>
      <br>

      <label for="{{ form.time.id_for_label }}">{{ form.time.label }}</label>
      {{ form.time|add_class:'form-control' }}
      {% for error in form.time.errors %}
        <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>

  <!-- Patient: {{ current.first_name }} {{current.last_name}}<br>
  Doctor: {{form.doctorid}}<br>
  Date: {{ form.date }}<br>
  Time: {{ form.time }}<br> -->
  <input id="submit" type="submit" value="Submit">

</form>
<script>
$(function () {
  $("#id_date").datepicker({
    format:'dd/mm/yyyy',
  });
});
</script>
{%endblock%}

templates/health/recep_book_appoint.html
{% extends 'health/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block headblock%}
<!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

  <!-- CDN for widget_tweaks -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
{% endblock %}

{% block topic1 %}
<a href="{% url 'recep_schedule' %}">Schedule</a>
{%endblock%}

{% block topic2 %}
<a href="{% url 'recep_book' %}">Book an appointment</a>
{%endblock%}

{% block bodyblock %}
<form  action="" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="{{ form.patient.id_for_label }}">{{ form.patient.label }}</label>
    {{ form.patient|add_class:'form-control' }}
    {% for error in form.patient.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}

    <label for="{{ form.doctorid.id_for_label }}">{{ form.doctorid.label }}</label>
    {{ form.doctorid|add_class:'form-control' }}
    {% for error in form.doctorid.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}

    <br><label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
    {{ form.date }}<br>
    {% for error in form.date.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}<br>

    <label for="{{ form.time.id_for_label }}">{{ form.time.label }}</label>
    {{ form.time|add_class:'form-control' }}
    {% for error in form.time.errors %}
      <span class="help-block">{{ error }}</span>
    {% endfor %}
  </div>

<input id="submit" type="submit" value="Submit">

  <script>
  $(function () {
    $("#id_date").datepicker({
      format:'dd/mm/yyyy',
    });
  });
</script>
</form>
{%endblock%}